---
- name: Ensure {{ grub_d_path }} is set to 700 and owned by root
  ansible.builtin.file:
    path: "{{ grub_d_path }}"
    state: directory
    mode: '0700'
    owner: root
    group: root
  tags:
    - grub
    - config

- name: Set GRUB_TIMEOUT
  ansible.builtin.lineinfile:
    path: "{{ grub_default_path }}"
    regexp: '^GRUB_TIMEOUT='
    line: "GRUB_TIMEOUT={{ grub_timeout }}"
    create: true
    mode: '0664'
  notify: Update grub
  tags:
    - grub
    - config

- name: Set GRUB_RECORDFAIL_TIMEOUT
  ansible.builtin.lineinfile:
    path: "{{ grub_default_path }}"
    regexp: '^GRUB_RECORDFAIL_TIMEOUT='
    line: "GRUB_RECORDFAIL_TIMEOUT={{ grub_recordfail_timeout }}"
    create: true
    mode: '0664'
  notify: Update grub
  tags:
    - grub
    - config

- name: Ensure file already exists at dest to work around invalid selinux context issue
  ansible.builtin.file:
    path: "{{ grub_boot_path }}/user.cfg"
    state: touch
    owner: root
    group: root
    setype: boot_t
    serole: object_r
    seuser: system_u
    mode: '0700'
    modification_time: preserve
    access_time: preserve
  tags:
    - grub
    - config

- name: Ensure GRUB password is set on RedHat systems
  ansible.builtin.lineinfile:
    path: "{{ grub_boot_path }}/user.cfg"
    regexp: '^GRUB2_PASSWORD='
    line: "GRUB2_PASSWORD={{ grub_password }}"
    create: true
    mode: '0700'
    owner: root
    group: root
    setype: boot_t
    serole: object_r
    seuser: system_u
  when:
    - grub_password is defined
    - ansible_facts['os_family'] == 'RedHat'
  notify: Update grub
  tags:
    - grub
    - config

- name: Ensure GRUB password is set on Debian
  ansible.builtin.blockinfile:
    path: "{{ grub_d_path }}/40_custom"
    marker: "# {mark} ANSIBLE MANAGED GRUB PASSWORD"
    create: true
    state: present
    mode: '0755'
    block: |
      set superusers="{{ grub_superuser }}"
      password_pbkdf2 {{ grub_superuser }} {{ grub_password }}
  when:
    - grub_password is defined
    - ansible_facts['os_family'] == 'Debian'
  notify: Update grub
  tags:
    - grub
    - config

- name: Set unrestricted option on grub
  ansible.builtin.lineinfile:
    path: "{{ grub_d_path }}/10_linux"
    regexp: 'CLASS="--class gnu-linux --class gnu --class os"'
    line: 'CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
  when: grub_password is defined
  notify: Update grub
  tags:
    - grub
    - config
