---
# handlers file for grub
- name: Update grub
  ansible.builtin.command: "{{ grub_update_grub_command }}"
  changed_when: true
  when: (ansible_facts['virtualization_type'] | default('')) not in _container_types
  notify: Reboot
  tags:
    - grub
    - service

- name: Reboot
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  when:
    - grub_allow_reboot
    - (ansible_facts['virtualization_type'] | default('')) not in _container_types
  tags:
    - grub
    - service
