---
- name: Verify grub role
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify grub default file exists
      ansible.builtin.stat:
        path: "{{ grub_default_path | default('/etc/default/grub') }}"
      register: grub_default_stat
      tags:
        - grub
        - validate

    - name: Assert grub default file exists
      ansible.builtin.assert:
        that:
          - grub_default_stat.stat.exists
        quiet: true
      tags:
        - grub
        - validate

    - name: Read grub default file
      ansible.builtin.slurp:
        path: "{{ grub_default_path | default('/etc/default/grub') }}"
      register: grub_default_file
      tags:
        - grub
        - validate

    - name: Assert grub timeout entries are present
      vars:
        grub_default_content: "{{ grub_default_file.content | b64decode }}"
      ansible.builtin.assert:
        that:
          - "'GRUB_TIMEOUT=5' in grub_default_content"
          - "'GRUB_RECORDFAIL_TIMEOUT=5' in grub_default_content"
        quiet: true
      tags:
        - grub
        - validate

    - name: Assert configured grub kernel options are present
      vars:
        grub_default_content: "{{ grub_default_file.content | b64decode }}"
      ansible.builtin.assert:
        that:
          - "'cgroup_enable=memory' in grub_default_content"
          - "'quiet' in grub_default_content"
          - "'some.option=complex,off' in grub_default_content"
        quiet: true
      tags:
        - grub
        - validate
